package com.metamapa.Domain.entities;

public enum EnumTipoEstadistica {
    MAXPROVINCIADEUNAPROVINCIA,
    MAXCATEGORIACONHECHOS,
    MAXPROVINCIASEGUNCONCATEGORIA,
    MAXHORASEGUNCATEGORIA,
    CANTSOLICITUDESSPAM
}
