package com.metamapa.Domain.entities;

public enum EnumTipoEstadistica {
    MAXPROVINCIADEUNACOLECCION,
    MAXCATEGORIACONHECHOS,
    MAXPROVINCIASEGUNCONCATEGORIA,
    MAXHORASEGUNCATEGORIA,
    CANTSOLICITUDESSPAM,
}
